fix: retornando userDTO
guilhXavier/agile-project-3a pull request #5
Opened 2024-04-13 14:59 UTC by edukatiau

2024-04-17 23:51 UTC, guilhXavier commented
I think this PR has modifications from another PR?

2024-04-18 11:22 UTC, guilhXavier requested changes
Take a look at the comments I've left

2024-04-18 11:22 UTC, guilhXavier commented on src/main/java/ifsul/agileproject/rachadinha/controller/UserController.java
> +        user.setPassword(dto.getPassword());
Can you take a look at the Object Mapper pattern for Java? That way, we don't have to build objects by hand like so

Here's [an example](https://github.com/guilhXavier/openfut/tree/main/src/main/java/br/com/gtx/openfut/mapper)

2024-04-18 11:22 UTC, guilhXavier commented on src/main/java/ifsul/agileproject/rachadinha/controller/UserController.java
> +    //Atualizar usuário pelo ID
Please remove these comments before the controller methods

2024-04-23 23:02 UTC, JPedro-M approved these changes

2024-05-02 23:04 UTC, guilhXavier approved these changes

2024-05-02 23:04 UTC, merged